typography_spectrum: 0.29816775280050933
color:
  brandColors:
    - '#FFFFFF'
    - '#050708'
    - '#ECDC21'
    - '#4B50A2'
    - '#25A97C'
  brandStrength: 0.9227648566011339
  lightness: 0.4449969807174057
  saturation: 0.4608145165257156
  rhythmicContrast: 0.3495143582113087
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5698485705070198
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bce9bc0d-7cef-4808-9d3d-9b0181cf5b05.png
name: PURO
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Só empatia não é suficiente (mas é um bom começo)
    id: 039878e0-815c-471c-9683-a1aabb1a6954
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/eb2d6766-ba02-42e1-98d4-ef8eeb380e5c.ico
title: PURO
description: 'Inovação, criatividade e pensamento'
purpose: []
