typography_spectrum: 0.66257
color:
  brandColors:
    - '#b41178'
    - '#ffffff'
    - '#008bcb'
    - '#eb7714'
    - '#d0cd00'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bce9bc0d-7cef-4808-9d3d-9b0181cf5b05.png
name: PURO
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/eb2d6766-ba02-42e1-98d4-ef8eeb380e5c.ico
title: PURO
description: 'Inovação, criatividade e pensamento'
purpose: []
