name: PURO
favicon: null
layout_spectrum: 0
typography_spectrum: 0.64302
title: PURO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e120d'
    - '#4a4d99'
    - '#9e0081'
    - '#f2df00'
    - '#35a174'
  brandStrength: 0.6299247029237449
  lightness: 0.6079167237039655
  saturation: 0.5179145878646523
  rhythmicContrast: 0.00870667234994471
purpose: []
